name: Build CLAM containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - containers/clam-core/**
      - containers/mutect2/**
      - .github/workflows/build-clam-core.yml

env:
  REGISTRY_ROOT: ghcr.io/${{ github.repository_owner }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build ${{ matrix.name }} linux/amd64 image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: clam-core
            context: containers/clam-core
          - name: clam-mutect2
            context: containers/mutect2

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CLAM container
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            CLAM_TARGETPLATFORM=linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY_ROOT }}/${{ matrix.name }}:0.1.0
            ${{ env.REGISTRY_ROOT }}/${{ matrix.name }}:latest
